#!/bin/bash
trap "echo -ne '\nstopping container...' && docker stop refinery-entry > /dev/null 2>&1 && echo -ne '\t\t [done]\n'" EXIT

docker stop refinery-entry

docker build -t refinery-entry-dev -f dev.Dockerfile .

docker run --rm -d \
--name refinery-entry \
--mount type=bind,source="$(pwd)"/,target=/usr/src/app \
--network dev-setup_default \
-e IS_OS=0 \
-e IS_DEMO=0 \
refinery-entry-dev

docker logs -f refinery-entry
